# Generated by Django 5.2.7 on 2025-11-05 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthtracker', '0005_alter_activity_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='status',
        ),
    ]
